Repository UrrrrKWANG/Kloudy, pull requests merged in 2022-10, with the labels that each got.

#41 Feat[#1] : Django Setting & 간단한 통신 실험
  kloudy/apis/__init__.py
  kloudy/apis/admin.py
  kloudy/apis/api_calls/weatherAPI.py
  kloudy/apis/apps.py
  kloudy/apis/migrations/0001_initial.py
  kloudy/apis/migrations/__init__.py
  kloudy/apis/models.py
  kloudy/apis/serializers.py
  kloudy/apis/tests.py
  kloudy/apis/urls.py
  kloudy/apis/views.py
  kloudy/kloudy/__init__.py
  kloudy/kloudy/asgi.py
  kloudy/kloudy/settings.py
  kloudy/kloudy/urls.py
  kloudy/kloudy/wsgi.py
  kloudy/manage.py
  kloudy/notifications/__init__.py
  kloudy/notifications/admin.py
  kloudy/notifications/apps.py
  kloudy/notifications/migrations/__init__.py
  kloudy/notifications/models.py
  kloudy/notifications/tests.py
  kloudy/notifications/views.py
  kloudy/requirements.txt
Labels: documentation, enhancement

#45 🎨 파일 구조를 생성하고, 필요한 Package 를 설치하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcodeproj/project.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy.xcodeproj/xcuserdata/youngjunlee.xcuserdatad/xcschemes/xcschememanagement.plist
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Application/Base.lproj/LaunchScreen.storyboard
  Kloudy/Kloudy/Application/SceneDelegate.swift
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/.xccurrentversion
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/Kloudy.xcdatamodel/contents
  Kloudy/Kloudy/Extension/Kloudy+Color.swift
  Kloudy/Kloudy/Extension/Kloudy+Font.swift
  Kloudy/Kloudy/Info.plist
  Kloudy/Kloudy/Model/Location.swift
  Kloudy/Kloudy/Model/Notification.swift
  Kloudy/Kloudy/Model/Weather.swift
  Kloudy/Kloudy/Model/WeatherCell.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/Contents.json
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellView.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellViewModel.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherCellView/AddWeatherCellView.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherCellView/AddWeatherCellViewModel.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherPageView/AddWeatherPageView.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherPageView/AddWeatherPageViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherCellView/SearchWeatherView.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherCellView/SearchWeatherViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherGridView/SearchWeatherGridView.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherGridView/SearchWeatherGridViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherListView/SearchWeatherListView.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherListView/SearchWeatherListViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SelectWeatherCellView/SelectWeatherCellView.swift
  Kloudy/Kloudy/View/AddWeather/SelectWeatherCellView/SelectWeatherCellViewModel.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionEditView/LocationSelectionEditView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionEditView/LocationSelectionEditViewModel.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckCityWeatherView/CheckCityView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckCityWeatherView/CheckCityViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherBasicNavigationView/CheckWeatherBasicNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherBasicNavigationView/CheckWeatherBasicNavigationViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherEditNavigationView/CheckWeatherEditNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherEditNavigationView/CheckWeatherEditNavigationViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherViewModel.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByFour/WeatherCellFourByFour.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByFour/WeatherCellFourByFourViewModel.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByOne/WeatherCellFourByOne.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByOne/WeatherCellFourByOneViewModel.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByTwo/WeatherCellFourByTwo.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByTwo/WeatherCellFourByTwoViewModel.swift
Labels: enhancement

#48 Feat: #47 import WidgetKit
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/KloudyWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  Kloudy/KloudyWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kloudy/KloudyWidget/Assets.xcassets/Contents.json
  Kloudy/KloudyWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Kloudy/KloudyWidget/Info.plist
  Kloudy/KloudyWidget/KloudyWidget.intentdefinition
  Kloudy/KloudyWidget/KloudyWidget.swift
Labels: enhancement

#49 Feat[#12, #14] : CheckWeatherBasicNavigationView, CheckWeatherEditNavigationView 의 Layout 을 구현하였습니다.
  Kloudy/Kloudy.xcodeproj/project.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/View/AddWeather/SelectWeatherCellView/SelectWeatherCellView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherBasicNavigationView/CheckWeatherBasicNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherEditNavigationView/CheckWeatherEditNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#51 Feat[#5] : Data Modeling을 완료했습니다.
  .DS_Store
  Kloudy/.DS_Store
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Application/SceneDelegate.swift
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/Kloudy.xcdatamodel/contents
  Kloudy/Kloudy/Model/CoreDataStack.swift
  Kloudy/Kloudy/Model/Location+CoreDataClass.swift
  Kloudy/Kloudy/Model/Location+CoreDataProperties.swift
  Kloudy/Kloudy/Model/Location.swift
  Kloudy/Kloudy/Model/Notification.swift
  Kloudy/Kloudy/Model/Weather.swift
  Kloudy/Kloudy/Model/WeatherCell+CoreDataClass.swift
  Kloudy/Kloudy/Model/WeatherCell+CoreDataProperties.swift
  Kloudy/Kloudy/Model/WeatherCell.swift
  Kloudy/Kloudy/ViewController.swift
Labels: enhancement

#50 Feat[#16] : CheckWeatherPageView frame 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/.DS_Store
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#55 Style[#54, #55] UIColor, UIFont Asset 과 Extension 을 추가하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcodeproj/project.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy.xcodeproj/xcuserdata/youngjunlee.xcuserdatad/xcschemes/xcschememanagement.plist
  Kloudy/Kloudy/Extension/Kloudy+Color.swift
  Kloudy/Kloudy/Extension/Kloudy+Font.swift
  Kloudy/Kloudy/Info.plist
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/BackgrundBlack.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Black.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/CellGray.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray03.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray04.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray05.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray06.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Gray07.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/OpacityOverlayBlack.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/PrimaryDarkGreen.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/PrimaryGreen.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/Red.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/White.colorset/Contents.json
  Kloudy/Kloudy/Resource/Font/Lexend-Regular.ttf
Labels: enhancement

#58 Revert "[Feat] #52 다양한 예시 위젯 추가"
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/KloudyWidget/KloudyIndexWidget/KloudyMaskWidget.swift
  Kloudy/KloudyWidget/KloudyIndexWidget/KloudyUmbrellaWidget.swift
  Kloudy/KloudyWidget/KloudyTodayWidget.swift
  Kloudy/KloudyWidget/KloudyWeeklyWidget.swift
  Kloudy/KloudyWidget/KloudyWidget.swift
Labels: enhancement

#57 Feat [#2] : Django 오늘의 날씨 보내주기
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Model/CityInformation.swift
  Kloudy/Kloudy/Model/FetchWeatherInformation.swift
  Kloudy/Kloudy/Model/Weather.swift
  Server/apis/api_calls/weatherAPI.py
  Server/apis/migrations/0001_initial.py
  Server/apis/models.py
  Server/apis/serializers.py
  Server/apis/views.py
Labels: enhancement

#60 [Feat] #52 위젯 종류 추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Info.plist
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
  Kloudy/kloudyWidget/kloudyWidget.intentdefinition
  Kloudy/kloudyWidget/kloudyWidget.swift
Labels: enhancement

#63 :sparkles: #62 LockScreen 위젯 추가
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
Labels: enhancement

#64 Feat[#2] 날씨 지수 보내주기
  Kloudy/.DS_Store
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Extension/CityInformation.csv
  Kloudy/Kloudy/Extension/FetchWeatherInformation.swift
  Kloudy/Kloudy/Model/CityInformation.swift
  Kloudy/Kloudy/Model/Weather.swift
  Server/apis/api_calls/weatherAPI.py
  Server/apis/migrations/0002_weatherindex_maskindex.py
  Server/apis/migrations/0003_rename_weatherindex_maskindex_weather_index.py
  Server/apis/models.py
  Server/apis/serializers.py
  Server/apis/views.py
Labels: enhancement

#69 Feat[#68] CheckWeatherCellLabelView 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCellLabelsView/CheckWeatherCellLabelView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
Labels: enhancement

#70 Feat[#18] Checklocationweatherview 구현
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
Labels: enhancement

#73 Feat[#65] : 생활 지수 추가 뷰 UI와 CoreData 로직을 구현하였습니다.
  .DS_Store
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcodeproj/project.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/Extension/Kloudy+Color.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/location.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/location.imageset/location.png
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/notification.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/notification.imageset/notification.png
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/setting.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/setting.imageset/setting.png
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCell.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellView.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherBasicNavigationView/CheckWeatherBasicNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#72 Feat[#9] : View - LocationSelectionView 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationSelectionCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#74 Feat [#71] : UILabel Extension 추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Extension/UILabel+.swift
Labels: enhancement

#79 Feat[#77] LocationManager 추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Model/LocationManager.swift
Labels: enhancement

#81 Feat[#78] : LocationSelectionView 에서 CityInformation.csv 파일을 파싱한 데이터를 UISearchBar 와 함께 TableView 에 표현하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/Extension/FetchWeatherInformation.swift
  Kloudy/Kloudy/Model/CityInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationTableCell.swift
Labels: enhancement

#85 Feat[#9] : LocationSelectionView 기능추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationSelectionCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionNavigationView/LocationSelectionNavigationView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionViewEditCell/LocationSelectionViewEditCell.swift
Labels: enhancement

#87 Bug[#9, #78] : Conflict 해결 도중에 중괄호를 지워버렸어서 이를 해결하였습니다.
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: bug

#93 Feat[#22, #23] CheckWeatherCollection 뷰 및 로직 구현
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherEditNavigationView/CheckWeatherEditNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
Labels: enhancement

#92 Feat[#84] : 새로운 Location 추가 시 요구되는 CoreData 로직들을 LocationSelectionViewModel 에 구현하였습니다.
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/Kloudy.xcdatamodel/contents
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellViewModel.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionViewModel.swift
Labels: enhancement

#95 Fix[#68] : CheckWeatherPageView 레이아웃 수정
  Kloudy/Kloudy/Extension/Kloudy+Color.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/BackgroundBlack.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/arrow_down.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/arrow_down@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/arrow_down@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/arrow_up.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/arrow_up@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/arrow_up@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudy.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudy.imageset/cloudy.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudy.imageset/cloudy@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudy.imageset/cloudy@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudySun.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudySun.imageset/cloudySun.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudySun.imageset/cloudySun@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/cloudySun.imageset/cloudySun@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/loaction_mark.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/loaction_mark.imageset/loaction_mark.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/loaction_mark.imageset/loaction_mark@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/loaction_mark.imageset/loaction_mark@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/rainy.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/rainy.imageset/rainy.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/rainy.imageset/rainy@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/rainy.imageset/rainy@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowRain.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowRain.imageset/_snowRain.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowRain.imageset/_snowRain@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowRain.imageset/_snowRain@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowy.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowy.imageset/snowy.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowy.imageset/snowy@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/snowy.imageset/snowy@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/sunny.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/sunny.imageset/sunny.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/sunny.imageset/sunny@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/sunny.imageset/sunny@3x.png
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCellLabelsView/CheckWeatherCellLabelView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
Labels: enhancement

#96 Design[#91] 위젯 테스트 이미지들 추가
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_1.imageset/mask_1.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_2.imageset/mask_2.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_3.imageset/mask_3.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/mask_4.imageset/mask_4.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_1.imageset/rain_1.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_2.imageset/rain_2.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_3.imageset/rain_3.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/rain_4.imageset/rain_4.png
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
  Kloudy/kloudyWidget/kloudyWidget.swift
Labels: enhancement

#98 Design[#97] App Icon 추가
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024 2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/120 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/128.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/196 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/loaction_mark.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/loaction_mark@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/loaction_mark@3x.png
Labels: enhancement

#100 Feat[#99] LockScreen 위젯 추가
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
Labels: enhancement

#101 Feat[#94] : CoreData 에 저장된 Location 을 LocationSelectionView 의 CollectionView 에 그리고, 날씨 데이터를 가져오는 함수를 수정하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/Extension/FetchWeatherInformation.swift
  Kloudy/Kloudy/Model/CityInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationSelectionCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionViewModel.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByTwo/AddLivingIndexCellView.swift
Labels: enhancement

#102 Feat[#11] : CheckWeatherView 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCellLabelsView/CheckWeatherCellLabelView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/TmpCheckWeatehrPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByTwo/AddLivingIndexCellView.swift
Labels: enhancement

#104 🩹 #11 CheckWeatherView CollectionView 기능 수정
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/TmpCheckWeatehrPageView.swift
Labels: enhancement

#105 Feat[#103] Location 의 날씨 정보를 불러오는 방식을 변경하였습니다.
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/Extension/FetchWeatherInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#107 :zap: #106 지역뷰 새로고침 기능 추가
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#109 Design[#108] 날씨이미지 추가
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-0.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-0.imageset/weather-5.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-1.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-1.imageset/weather-2.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-2.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-2.imageset/weather-1.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-3.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-3.imageset/weather-3.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-4.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-4.imageset/weather-3.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-5.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/weather/weather-5.imageset/weather-4.svg
Labels: enhancement

#113 Design [#54] UIFont Extension 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
Labels: enhancement

#115 Feat[#20, #114] : CheckLocationWeatherView에 날씨 데이터 받는 기능 추가
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#117 Feat[#9] location selection view 셀 변경 작업중 중간 저장용 pr
  .DS_Store
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionEditView/LocationSelectionEditView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionViewEditCell/LocationSelectionViewEditCell.swift
Labels: enhancement

#120 Fix[#43] location selection view 셀 변경 작업중 오류나는 부분 수정
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationSelectionCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: bug

#121 Feat[#118] : 날씨 파일명 변경
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_0.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_0.imageset/sunny.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_0.imageset/sunny@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_0.imageset/sunny@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_1.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_1.imageset/rainy.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_1.imageset/rainy@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_1.imageset/rainy@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_2.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_2.imageset/_snowRain.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_2.imageset/_snowRain@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_2.imageset/_snowRain@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_3.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_3.imageset/cloudySun.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_3.imageset/cloudySun@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_3.imageset/cloudySun@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_4.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_4.imageset/cloudy.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_4.imageset/cloudy@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_4.imageset/cloudy@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_5.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_5.imageset/snowy.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_5.imageset/snowy@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/currentWeather_5.imageset/snowy@3x.png
Labels: enhancement

#122 Feat [#17] CheckWeatherPageView lottie 및 image 로직 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/TmpCheckWeatehrPageView.swift
Labels: enhancement

#123 Feat[#116] 앱 설치 후 첫 실행 시 종로구를 CoreData 의 Location 으로 저장되도록 하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/Resource/Assets.xcassets/rainIndex.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/rainIndex.imageset/rain_2.png
  Kloudy/Kloudy/View/AddWeather/.DS_Store
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCell.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellView.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/.DS_Store
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#125 Feat[#124] CheckLocationWeatherView UI 수정
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
Labels: enhancement

#126 Feat[#43] 위치선택뷰 컬렉션셀 UI 완성
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationSelectionCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#128 Design[#119] CheckWeatherView 레이아웃 수정
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/TmpCheckWeatehrPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#129 Feat[#127] 지역 삭제 기능 추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Protocol+/Protocol+.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationSelectionCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionViewModel.swift
Labels: enhancement

#130 Feat[#124] CheckWeatherView 세부 레이아웃 수정
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement
