Repository UrrrrKWANG/Kloudy, pull requests merged in 2022-11, with the labels that each got.

#133 Refactor[#132] Sprint 2 를 위한 프로젝트 파일 디렉터리 개선
  .DS_Store
  Kloudy/.DS_Store
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Kloudy/.DS_Store
  Kloudy/Kloudy/Base.lproj/Main.storyboard
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/Extension/.DS_Store
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Extension/Font+.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/Protocol/Protocol+.swift
  Kloudy/Kloudy/Resource/CityInformation.csv
  Kloudy/Kloudy/View/.DS_Store
  Kloudy/Kloudy/View/AddWeather/.DS_Store
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCell.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellView.swift
  Kloudy/Kloudy/View/AddWeather/AddLivingIndexCellView/AddLivingIndexCellViewModel.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherCellView/AddWeatherCellView.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherCellView/AddWeatherCellViewModel.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherPageView/AddWeatherPageView.swift
  Kloudy/Kloudy/View/AddWeather/AddWeatherPageView/AddWeatherPageViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherCellView/SearchWeatherView.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherCellView/SearchWeatherViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherGridView/SearchWeatherGridView.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherGridView/SearchWeatherGridViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherListView/SearchWeatherListView.swift
  Kloudy/Kloudy/View/AddWeather/SearchWeatherListView/SearchWeatherListViewModel.swift
  Kloudy/Kloudy/View/AddWeather/SelectWeatherCellView/SelectWeatherCellView.swift
  Kloudy/Kloudy/View/AddWeather/SelectWeatherCellView/SelectWeatherCellViewModel.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionEditView/LocationSelectionEditView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionEditView/LocationSelectionEditViewModel.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionViewModel.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/SearchLocationView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionViewEditCell/LocationSelectionViewEditCell.swift
  Kloudy/Kloudy/View/CheckWeather/CheckCityWeatherView/CheckCityView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckCityWeatherView/CheckCityViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckLocationWeatherView/CheckLocationWeatherViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCellLabelsView/CheckWeatherCellLabelView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherCollectionView/CheckWeatherCollectionViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherEditNavigationView/CheckWeatherEditNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherEditNavigationView/CheckWeatherEditNavigationViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/CheckWeatherPageViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherPageView/TmpCheckWeatehrPageView.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByFour/WeatherCellFourByFour.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByFour/WeatherCellFourByFourViewModel.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByOne/WeatherCellFourByOne.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByOne/WeatherCellFourByOneViewModel.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByTwo/WeatherCellFourByTwo.swift
  Kloudy/Kloudy/View/WeatherCells/WeatherCellFourByTwo/WeatherCellFourByTwoViewModel.swift
  Kloudy/Kloudy/ViewController.swift
Labels: Refactoring

#136 Design[#135] CheckWeatherView 레이아웃 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#138 Fix[#135] CheckWeatherView 레이아웃 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: bug

#139 Feat[#132] Charts, FSPagerView 라이브러리 추가
  Kloudy/Kloudy.xcworkspace/xcuserdata/youngjunlee.xcuserdatad/UserInterfaceState.xcuserstate
  Kloudy/Podfile
  Kloudy/Podfile.lock
  Kloudy/Pods/Manifest.lock
  Kloudy/Pods/Pods.xcodeproj/project.pbxproj
  Kloudy/Pods/Pods.xcodeproj/xcuserdata/youngjunlee.xcuserdatad/xcschemes/xcschememanagement.plist
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-acknowledgements.markdown
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-acknowledgements.plist
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-frameworks-Debug-input-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-frameworks-Debug-output-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-frameworks-Release-input-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-frameworks-Release-output-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests-frameworks.sh
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests.debug.xcconfig
  Kloudy/Pods/Target Support Files/Pods-Kloudy-KloudyUITests/Pods-Kloudy-KloudyUITests.release.xcconfig
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-acknowledgements.markdown
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-acknowledgements.plist
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-frameworks-Debug-input-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-frameworks-Debug-output-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-frameworks-Release-input-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-frameworks-Release-output-files.xcfilelist
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy-frameworks.sh
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy.debug.xcconfig
  Kloudy/Pods/Target Support Files/Pods-Kloudy/Pods-Kloudy.release.xcconfig
  Kloudy/Pods/Target Support Files/Pods-KloudyTests/Pods-KloudyTests.debug.xcconfig
  Kloudy/Pods/Target Support Files/Pods-KloudyTests/Pods-KloudyTests.release.xcconfig
Labels: enhancement

#145 Design[#108] 날씨이미지 추가
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-0.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-0.imageset/detailWeather-0.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-0.imageset/detailWeather-0x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-0.imageset/detailWeather-0x3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/detailWeather-1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/detailWeather-1x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/detailWeather-1x3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/detailWeather-2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/detailWeather-2x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/detailWeather-2x3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-3.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-3.imageset/detailWeather-3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-3.imageset/detailWeather-3x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-3.imageset/detailWeather-3x3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-4.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-4.imageset/detailWeather-4.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-4.imageset/detailWeather-4x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-4.imageset/detailWeather-4x3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-5.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-5.imageset/detailWeather-5.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-5.imageset/detailWeather-5x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-5.imageset/detailWeather-5x3.png
Labels: enhancement

#147 Feat[#142] RxSwift 를 활용하여 LocationSelecationView 에서 Location SearchBar 에서 발생하는 이벤트를 주시합니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/magnifyingGlass.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/NavigationIcon/magnifyingGlass.imageset/magnifyingGlass.png
  Kloudy/Kloudy/View/.DS_Store
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/SearchLocationView/LocationSearchBar.swift
  Kloudy/Kloudy/View/CheckLocation/SearchLocationView/LocationTableCell.swift
Labels: enhancement

#150 Feat[#149] 변경된 Location 모델에 대한 CoreData 의 로직을 수정하고, LocationSelectionView 에 변경된 로직을 적용하였습니다.
  .DS_Store
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/Kloudy.xcdatamodel/contents
  Kloudy/Kloudy/Model/Location+CoreDataProperties.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#157 Feat[#156] DetailWeatherView UI 및 VM 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewCollectionViewCells/TodayWeatherDataCell.swift.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewCollectionViewCells/WeekWeatherDataCell.swift.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewModel.swift
Labels: enhancement

#159 Feat [#154] WeatherIndexView 제작
  Kloudy/Kloudy/Extension/Font+.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#167 Feat[#131] : Django 백엔드 리팩토링 했습니다.
  .DS_Store
  Kloudy/.DS_Store
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Podfile
  Server/apis/api_calls/weatherAPI.py
  Server/apis/migrations/0001_initial.py
  Server/apis/migrations/0002_weatherindex_maskindex.py
  Server/apis/migrations/0003_rename_weatherindex_maskindex_weather_index.py
  Server/apis/models.py
  Server/apis/serializers.py
  Server/apis/views.py
  Server/kloudy/__init__.py
  Server/kloudy/apps.py
  Server/kloudy/csv/Locations.csv
  Server/kloudy/networkAPI.py
  Server/kloudy/scheduler/__init__.py
  Server/kloudy/scheduler/scheduler.py
  Server/kloudy/settings.py
  Server/kloudy/views.py
Labels: enhancement, Refactoring

#175 Feat[#174] settingView 생성
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: enhancement

#171 Fix[#170] Asset명(색상이름) 오류로 인해 빌드되지 않는 현상 해결
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationTableViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionNavigationView/LocationSelectionNavigationView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/SearchLocationView/LocationSearchBar.swift
  Kloudy/Kloudy/View/CheckLocation/SearchLocationView/LocationTableCell.swift
Labels: bug

#179 Feat[#178] : Django Hotfix 날씨를 갱신할 때 local_weather가 갱신되는 것이 아니라 새롭게 추…
  Server/kloudy/scheduler/scheduler.py
  Server/kloudy/views.py
Labels: bug

#183 Feat[#182] : WeatehrIndexView 구현
  .DS_Store
  Kloudy/.DS_Store
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/White.colorset/Contents.json
  Kloudy/Kloudy/View/CheckWeather/.DS_Store
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/.DS_Store
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewCell/InternalIndexViewCell.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewModel.swift
Labels: enhancement

#186 Fix[#177] 테이블뷰가 스크롤될때 검색창을 덮어버리는 문제를 해결했습니다.
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: bug

#193 Design[#53] : internalIndex color asset 추가
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexBlue01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexBlue02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexCyan01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexCyan02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexGray01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexGray02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexGreen01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexGreen02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexRed01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexRed02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexYellow01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/InternalIndexYellow02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/InternalIndexGreen02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/PrimaryBlue07.colorset/Contents.json
Labels: enhancement

#192 Design[#190] : internalIndex image assets 추가
  Kloudy/Kloudy/Resource/Assets.xcassets/InternalIndexGreen02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/PrimaryBlue07.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/coldWave.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/coldWave.imageset/coldWave.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/coldWave.imageset/coldWave2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/coldWave.imageset/coldWave3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/freezeAndBurst.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/freezeAndBurst.imageset/freezeAndBurst.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/freezeAndBurst.imageset/freezeAndBurst2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/freezeAndBurst.imageset/freezeAndBurst3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/pollen.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/pollen.imageset/pollen.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/pollen.imageset/pollen2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/pollen.imageset/pollen3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/strongWind.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/strongWind.imageset/strongWind.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/strongWind.imageset/strongWind2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/strongWind.imageset/strongWind3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/typhoon.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/typhoon.imageset/typhoon.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/typhoon.imageset/typhoon2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/typhoon.imageset/typhoon3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/yellowDust.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/yellowDust.imageset/yellowDust.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/yellowDust.imageset/yellowDust2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/internalIndexImages/yellowDust.imageset/yellowDust3x.png
Labels: enhancement

#195 Feat[#194] : Rx 를 활용하여 API 를 통해 서버에 데이터를 요청하는 로직을 구현하고, Codable 프로토콜을 준수하는 구조체를 형성하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Model/Weather.swift
  Kloudy/Kloudy/Network/CityWeatherAPI.swift
  Kloudy/Kloudy/Network/CityWeatherNetwork.swift
Labels: enhancement

#198 Feat : Umbrella Index 모델에 오타수정.
  Server/apis/migrations/0001_initial.py
  Server/apis/models.py
  Server/apis/serializers.py
  Server/apis/views.py
  Server/kloudy/scheduler/scheduler.py
  Server/kloudy/views.py
Labels: bug

#200 Feat : 우산 지수 오타 수정, 세차지수 변경
  Server/apis/migrations/0001_initial.py
  Server/apis/models.py
  Server/kloudy/apps.py
  Server/kloudy/csv/Locations.csv
  Server/kloudy/views.py
Labels: bug

#202 Feat[#194] : 변경된 JSON 파일에 대응하여 Codable 구조체를 수정하였습니다.
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Model/Weather.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
Labels: enhancement

#204 Bug[#203] : LocationManager 오류 수정
  Kloudy/Kloudy/Model/LocationManager.swift
Labels: bug

#206 :bento: #205 Lottie file 추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Lottie/carwash/.DS_Store
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step1.json
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step2.json
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step3.json
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step4.json
  Kloudy/Kloudy/Resource/Lottie/laundry/.DS_Store
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_1.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_2.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_3.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_4.json
  Kloudy/Kloudy/Resource/Lottie/mask/.DS_Store
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step1.png
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step2.png
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step3.png
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step4.json
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step1.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step2.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step3.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step4.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step5.png
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step1.json
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step2.json
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step3.json
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step4.json
Labels: enhancement

#210 Style[#209] : Weather index view 코드정리
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewModel.swift
Labels: enhancement

#212 Design[#211] Widget Image Add
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_1.imageset/IMG_3165.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_2.imageset/IMG_3168.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_3.imageset/IMG_3167.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_4.imageset/IMG_3166.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_1.imageset/IMG_2CAAFD238497-1.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_2.imageset/IMG_C192A8C36490-1.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_3.imageset/IMG_2DAB7E19FCB2-1.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_4.imageset/IMG_A678926AEA10-1.svg
Labels: enhancement

#213 Feat : 런치스크린에서 미리 AppDelegate에 날씨 정보를 받아오게 했습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Application/Base.lproj/LaunchScreen.storyboard
  Kloudy/Kloudy/Application/SceneDelegate.swift
  Kloudy/Kloudy/Model/LocationConverter.swift
  Kloudy/Kloudy/Model/LocationManager.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Server/kloudy/apps.py
  Server/kloudy/views.py
Labels: enhancement

#217 Feat[#216] 내부지수의 개수와 유형을 파악하는 로직 구현
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewModel.swift
Labels: enhancement

#219 Feat : 현재 위경도를 기반으로 XY값을 계산, XY값으로 위치 정보를 찾는 로직
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Model/CityInformation.swift
  Kloudy/Kloudy/Model/LocationConverter.swift
  Kloudy/Kloudy/Model/LocationManager.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/Resource/Localization/CityInformation.csv
Labels: Refactoring

#222 Feat[#221] : WeatherIndexView collectionView layer, UI 디테일, 코드 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewCollectionViewCells/TodayWeatherDataCell.swift.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewCollectionViewCells/WeekWeatherDataCell.swift.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewCell/InternalIndexCollectionViewCell.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewCell/InternalIndexViewCell.swift
Labels: enhancement

#224 Feat[#223] api값 CheckWeatherView에 연결
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
Labels: enhancement

#227 Feat[#225] CheckWeatherView 지역 변경 시 필요한 코드 추가
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#229 Design[#228] CurrentWeatherView에서 사용할 asset 추가
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorSet/PrimaryBlue08.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/arrow_down.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/arrow_down@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_down.imageset/arrow_down@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/arrow_up.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/arrow_up@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/arrow_up.imageset/arrow_up@3x.png
Labels: enhancement

#231 Feat[#230] : 지역 날씨 데이터 연결
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: enhancement

#233 Feat[#226] : API 를 통해 서버로부터 전달 받은 데이터를 WeatherIndexDetailView 로 전달하였습니다.
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexButtonView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexChartView/IndexChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexIconView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement

#236 Feat[#172] 셀 위치 변경시 코어데이터에 반영
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/Extension/NSManagedObject+.swift
  Kloudy/Kloudy/Model/LocationData.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#237 Feat[#232] WeatherIndexView 내의 indexCollectionView CoreData 로직 구현 및 세부사항 조정
  Kloudy/Kloudy/CoreData/.DS_Store
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/Kloudy.xcdatamodel/contents
  Kloudy/Kloudy/Model/CityInformation.swift
  Kloudy/Kloudy/Model/Location+CoreDataProperties.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/.DS_Store
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#238 Style: fix remove constraint
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: bug

#240 Feat #239 저장된 지역순으로 View를 그리는 로직 구현
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#244 Fix[#243] Widget 이미지 수정
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_1.imageset/IMG_3165.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_1.imageset/IMG_3165.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_2.imageset/IMG_3168.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_2.imageset/IMG_3168.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_3.imageset/IMG_3167.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_3.imageset/IMG_3167.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_4.imageset/IMG_3166.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/carwash_4.imageset/IMG_3166.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_1.imageset/IMG_2CAAFD238497-1.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_1.imageset/IMG_2CAAFD238497-1.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_2.imageset/IMG_C192A8C36490-1.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_2.imageset/IMG_C192A8C36490-1.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_3.imageset/IMG_2DAB7E19FCB2-1.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_3.imageset/IMG_2DAB7E19FCB2-1.svg
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_4.imageset/IMG_A678926AEA10-1.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/laundry_4.imageset/IMG_A678926AEA10-1.svg
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
Labels: bug

#242 Design[#234] CurrentWeatherView 최고 최저온도 UI추가
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/Group 138.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/Group 138@2x.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/Group 138@3x.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/location_mark.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/location_mark@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/WeatherIcon/location_mark.imageset/location_mark@3x.png
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
Labels: enhancement

#245 Feat[#241] : 지역이 추가 및 삭제되었을 때 지역의 날씨 데이터를 서버에 요청 및 변경하여, 이를 바탕으로 메인 뷰를 다시 그립니다.
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#253 Feat[#241, #235] : Location 을 삭제하고 메인 뷰로 돌아갔을 때 앱이 동작하지 않는 이슈를 해결하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/CoreData/Kloudy.xcdatamodeld/Kloudy.xcdatamodel/contents
  Kloudy/Kloudy/Resource/Lottie/laundry/.DS_Store
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#255 Feat[#254] : Widget upgrade
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyCarWashIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyLaundryIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyOuterIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
  Kloudy/kloudyWidget/kloudyWidget.swift
Labels: enhancement

#257 Feat : 우산 인덱스에서 시간별 강수량을 보내줍니다.
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/150.png
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/Contents.json
  Server/apis/migrations/0001_initial.py
  Server/apis/models.py
  Server/apis/serializers.py
  Server/kloudy/scheduler/scheduler.py
  Server/kloudy/views.py
Labels: Refactoring

#259 Style[#258] Image에 default 값을 줬습니다.
  Kloudy/Kloudy/Resource/Assets.xcassets/defaultImage/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/defaultImage/caution.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/defaultImage/caution.imageset/caution.svg
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexIconView.swift
Labels: enhancement

#260 Feat[#256] LocationWeatherIndexView의 changeTextView 구현
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#265 Design[#108] : 지수 이미지 추가
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/carwash.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/carwash@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/carwash@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/laundry.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/laundry@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/laundry@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/mask.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/mask@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/mask@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/outer.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/outer@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/outer@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/umbrella.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/umbrella@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/umbrella@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/updown.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/updown@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/updown@3x.png
Labels: enhancement

#266 Feat[#262] : LocationSelectionView 의 TableView 가 그려지는 방식을 변경하고, 지역 추가 시 비동기 처리를 통해 Cell 의 데이터를 표현하였습니다.
  .DS_Store
  Kloudy/Kloudy.xcodeproj/xcuserdata/youngjunlee.xcuserdatad/xcschemes/xcschememanagement.plist
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Protocol/Protocol+.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
Labels: enhancement

#272 Feat[#270] iOS 16 미만일때 LockScreen Widget을 사용하지 못하도록 합니다.
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyCarWashIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyLaundryIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyOuterIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
Labels: enhancement

#274 Feat[#273] iOS 최소 지원버전을 14로 내립니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
Labels: enhancement

#278 Feat[#277] : 아이콘 호출 및 isSelect 되었을 때 배경색을 주는 로직 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/Contents.json
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewCell/indexCollectionViewCell.swift
Labels: enhancement

#264 Refactor[#261] 현재온도, 최고온도, 최저온도 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Extension/LocalWeather+.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: Refactoring

#281 Fix[#258] count var로 수정
  Kloudy/Kloudy/Extension/LocalWeather+.swift
Labels: bug

#280 design #279 sprint2에서 사용하지 않을 UI 정리
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherBasicNavigationView/CheckWeatherBasicNavigationView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#276 UI : Launch Screen UI를 수정했습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Application/Base.lproj/LaunchScreen.storyboard
  Kloudy/Kloudy/Application/SceneDelegate.swift
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024 2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/120 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/128.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/128x128.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/136.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/136x136.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/152x152.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/192.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/192x192.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/196 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/196.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/76x76.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-114.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-120 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-128.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/150.png
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/logo.png
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: enhancement, Refactoring

#290 Feat[#289] 앱 이름을 구르미로 변경하였습니다!
  .gitignore
  Kloudy/Kloudy.xcodeproj/project.pbxproj
Labels: enhancement

#291 Fix[#286] AppDelegate-defaultData추가
  Kloudy/Kloudy/Application/AppDelegate.swift
Labels: bug

#292 UI : Setting View Cell 라벨 줄넘김 수정
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/View/Setting/LicenseCellView.swift
Labels: bug

#295 Design[#294] : Lottie 파일 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step1.json
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step2.json
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step3.json
  Kloudy/Kloudy/Resource/Lottie/carwash/carwash_step4.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_1.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_2.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_3.json
  Kloudy/Kloudy/Resource/Lottie/laundry/laundry_4.json
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step1.png
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step2.png
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step3.png
  Kloudy/Kloudy/Resource/Lottie/mask/mask_step4.json
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step1.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step2.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step3.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step4.png
  Kloudy/Kloudy/Resource/Lottie/outer/outer_step5.png
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step1.json
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step2.json
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step3.json
  Kloudy/Kloudy/Resource/Lottie/rain/rain_step4.json
Labels: enhancement

#296 Feat: Localization 추가, setting view 네비게이션뷰 constraints 수정
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Extension/String+.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/Resource/Localization/CityInformation_KOR.csv
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/Resource/Localization/ko.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationTableViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionNavigationView/LocationSelectionNavigationView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/SearchLocationView/LocationSearchBar.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexChartView/IndexChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexStepView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/Setting/SettingLicenseNavigationView.swift
  Kloudy/Kloudy/View/Setting/SettingLicenseView.swift
  Kloudy/Kloudy/View/Setting/SettingNavigationView.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: enhancement

#299 Feat[#263] : 앱 설치 후 첫 구동 시 종로구가 CoreData 에 저장하였습니다.
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckLocation/SearchLocationView/LocationSearchBar.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement

#297 Bug : Location, Setting Navigation뷰의 뒤로가기버튼 버그 수정
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionNavigationView/LocationSelectionNavigationView.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/Setting/SettingLicenseNavigationView.swift
  Kloudy/Kloudy/View/Setting/SettingLicenseView.swift
  Kloudy/Kloudy/View/Setting/SettingNavigationView.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: bug

#301 Bug : Swipe Back을 막았습니다.
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: bug

#304 Feat: first cell에 위치 동의 문구 넣기, 클릭시 위치 사용 동의 띄우기
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/CurrentLocationTableViewCell.swift
Labels: enhancement

#305 Feat[#287] UmbrellaIndexText 추가
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement

#308 Feat[#298] : internalIndexCollectionView UI 띄웁니다.
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: bug

#309 Fix: 상세날씨뷰 추가 로컬라이제이션
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: enhancement

#310 Fix: locationSelectionView 셀 분기처리
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#307 Feat[#271] : AppDelegate 에 위치 권한 및 CoreData 갯수에 따른 로직을 수정하였습니다.
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#312 Fix[#311] : 출시 전 발생하는 이슈를 개선하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement

#314 Feat[#313] InfoPlist 번역
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Info.plist
  Kloudy/Kloudy/Resource/Localization/en.lproj/InfoPlist.strings
  Kloudy/Kloudy/Resource/Localization/ko.lproj/InfoPlist.strings
Labels: enhancement

#320 Feat[#319] : Location 들의 기상 정보를 서버에 요청하고 모두 불러왔을 때 메인 화면으로 넘어가도록 구현하였습니다.
  Kloudy/Kloudy/Application/AppDelegate.swift
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: enhancement

#327 Feat[#324] : 지역 추가/삭제/위치 이동 시 발생하는 이슈 개선 및 현재 위치 동의 여부에 따른 지역 Cell 분기 처리
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/CurrentLocationTableViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionCollectionViewCell/LocationTableViewCell.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
Labels: bug, enhancement

#329 Feat[#322] 전날대비온도 지수 내 차트 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Extension/Font+.swift
  Kloudy/Kloudy/Extension/LocalWeather+.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: enhancement

#338 Feat[#331] 우산지수 텍스트 코드 개선
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorAssets/Orange01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorAssets/PrimaryBlue07.colorset/Contents.json
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement, Refactoring

#336 design #335 weatherIndexView 세부 디자인 수정
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/carwash.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/carwash@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/carwash.imageset/carwash@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/laundry.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/laundry@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/laundry.imageset/laundry@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/mask.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/mask@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/mask.imageset/mask@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/outer.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/outer@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/outer.imageset/outer@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/umbrella.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/umbrella@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/umbrella.imageset/umbrella@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/updown.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/updown@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/updown.imageset/updown@3x.png
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewCell/indexCollectionViewCell.swift
Labels: enhancement

#337 Feat[#334] : Widget 디자인을 반영하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/locaition.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/locaition.imageset/locaition.png
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyCarWashIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyLaundryIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyOuterIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
  Kloudy/kloudyWidget/KloudyWarningWidget.swift
  Kloudy/kloudyWidget/kloudyWidget.swift
Labels: enhancement

#342 Design[#341] : LockScreen Widget 이미지 추가
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_1.imageset/lock_car_1.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_2.imageset/lock_car_2.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_3.imageset/lock_car_3.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_car_4.imageset/lock_car_4.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_1.imageset/lock_laundry_1.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_2.imageset/lock_laundry_2.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_3.imageset/lock_laundry_3.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_laundry_4.imageset/lock_laundry_4.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_1.imageset/lock_mask_1.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_2.imageset/lock_mask_2.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_3.imageset/lock_mask_3.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_mask_4.imageset/lock_mask_4.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_1.imageset/lock_outer_1.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_2.imageset/lock_outer_2.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_3.imageset/lock_outer_3.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_4.imageset/lock_outer_4.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_5.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_outer_5.imageset/lock_outer_5.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_1.imageset/lock_rain_1.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_2.imageset/lock_rain_2.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_3.imageset/lock_rain_3.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_rain_4.imageset/lock_rain_4.png
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/lockWarning.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/WidgetImage/lockWarning.imageset/lockWarning.png
Labels: enhancement

#340 Design[#339] TemperatureGapView의 UI 수정, 영하일 때 버그 수정
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_down.imageset/max_down.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_down.imageset/max_down@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_down.imageset/max_down@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_same.imageset/max_same.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_same.imageset/max_same@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_same.imageset/max_same@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_up.imageset/max_up.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_up.imageset/max_up@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/max_up.imageset/max_up@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_down.imageset/min_down.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_down.imageset/min_down@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_down.imageset/min_down@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_same.imageset/min_same.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_same.imageset/min_same@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_same.imageset/min_same@3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_up.imageset/min_up.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_up.imageset/min_up@2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/indexImages/temperaturegap/min_up.imageset/min_up@3x.png
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: bug, Refactoring

#344 Feat[#343] : LockScreen Widget 디자인 반영
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lockWarning.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lockWarning.imageset/lockWarning.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_1.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_1.imageset/lock_car_1.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_2.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_2.imageset/lock_car_2.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_3.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_3.imageset/lock_car_3.png
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_4.imageset/Contents.json
  Kloudy/kloudyWidget/Assets.xcassets/LockScreenWidgetImage/lock_carwash_4.imageset/lock_car_4.png
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyIndexAccessoryCircularWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyUmbrellaIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidgets/KloudyCarWashIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidgets/KloudyLaundryIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidgets/KloudyMaskIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidgets/KloudyOuterIndexWidget.swift
  Kloudy/kloudyWidget/KloudyIndexWidgets/KloudyUmbrellaIndexWidget.swift
  Kloudy/kloudyWidget/KloudyWarningWidget/KloudyWarningAccessoryCircularWidget.swift
  Kloudy/kloudyWidget/KloudyWarningWidget/KloudyWarningWidget.swift
Labels: enhancement
