Repository UrrrrKWANG/Kloudy, pull requests merged in 2022-12, with the labels that each got.

#347 Feat[#346, #317] 앱 실행 시 현재 위치 정보 수집 권한 설정 확인 후 서버에 현재 위치 기상 데이터 요청/전달 및 인터넷 연결이 되어있지 않을 경우에 대한 UI 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/NetworkUnreachableView.swift
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/Network/NetworkReachability.swift
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexChartView/IndexChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#348 Feat[#315] 내부지수 collectionView - index out of range 해결
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#351 Feat[#316] : 모달로 구현되어 있는 상세 페이지를 상하 좌우로 확인할 수 있도록 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Extension/Font+.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/detailWeather-2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/detailWeather-2x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-1.imageset/detailWeather-2x3.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/detailWeather-1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/detailWeather-1x2.png
  Kloudy/Kloudy/Resource/Assets.xcassets/detailViewWeatherImages/detailWeather-2.imageset/detailWeather-1x3.png
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/InternalCheckWeatherPageView/InternalCheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewModel.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#354 Feat[#315] : 지수 뷰 우측 상단 CollectionView 코드 정리
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#358 Feat: Localization
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: enhancement

#360 Feat: Localization 최종 추가
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
Labels: enhancement

#362 Fix[#361] 일교차 지수 레이아웃 수정
  Kloudy/Kloudy/Extension/LocalWeather+.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: Refactoring

#363 Feat[#316] : pageView 변경
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/InternalCheckWeatherPageView/InternalCheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#356 Refactoring [#250] : Django Refactoring했습니다.
  Server/kloudy/views.py
  Server/kloudy/weathers/CarWashIndex.py
  Server/kloudy/weathers/CompareIndex.py
  Server/kloudy/weathers/HourlyWeather.py
  Server/kloudy/weathers/LaundryIndex.py
  Server/kloudy/weathers/MainWeather.py
  Server/kloudy/weathers/MaskIndex.py
  Server/kloudy/weathers/OuterIndex.py
  Server/kloudy/weathers/UmbrellaIndex.py
  Server/kloudy/weathers/WeeklyWeather.py
  Server/kloudy/weathers/__init__.py
Labels: Refactoring

#364 Fix: Localization drizzle을 rain shower로 수정
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
Labels: enhancement

#366 Feat[#350, #352] : 온보딩 뷰를 구현하고, Location 순서 변경 시 indexArray 도 수정되도록 변경하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/Base.lproj/LaunchScreen.storyboard
  Kloudy/Kloudy/Application/OnboardingPageView.swift
  Kloudy/Kloudy/Application/OnboardingView.swift
  Kloudy/Kloudy/CoreData/CoreDataManager.swift
  Kloudy/Kloudy/Extension/Font+.swift
  Kloudy/Kloudy/Model/LocationData.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding1.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding1.imageset/onboardingA1x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding1.imageset/onboardingA2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding1.imageset/onboardingA3x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding2.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding2.imageset/onboardingB1x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding2.imageset/onboardingB2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/OnboardingImage/onboarding2.imageset/onboardingB3x.png
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#359 Design[#355] : 디자인 부분 변경
  Kloudy/kloudyWidget/KloudyIndexWidget/KloudyIndexWidget.swift
Labels: enhancement

#372 Fix[#369, #370, #371] 일교차 지수 버그 수정, 불필요한 코드 제거, 온도 원래 값으로 수정
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CurrentWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/InternalCheckWeatherPageView/InternalCheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: bug, Refactoring

#368 Feat: 온보딩 로컬라이제이션 추가
  Kloudy/Kloudy/Application/OnboardingView.swift
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
Labels: enhancement

#375 Feat[#346] : 백그라운드에서 현재 위치 정보 권한 변경 시, 이를 주시하며 일련의 처리 과정을 수행합니다.
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/Setting/SettingLocationAllowCellView.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: enhancement

#380 Feat[#379] : 현재 날씨 온도 맞지 않는 이슈 및 주간 날씨의 텍스트 수정
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: enhancement

#381 Style[#151] : 앱 로고 및 LaunchScreen 이미지 수정
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/120 1.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/128.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/128x128.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/136.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/136x136.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/152x152.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/192.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/192x192.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/76x76.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Kloudy/Kloudy/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/NoBackground1x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/NoBackground2x.png
  Kloudy/Kloudy/Resource/Assets.xcassets/logo.imageset/NoBackground3x.png
Labels: enhancement

#378 Feat[#367] : 내부지수 토스트 메세지 구현
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexViewCell/InternalIndexCollectionViewCell.swift
Labels: enhancement

#383 Style[#382] : 하단 타이틀 온도 레이아웃 수정
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: enhancement

#384 Refactoring[#365] : WeatherKit API로 리팩토링하기
  .DS_Store
  .gitignore
  Kloudy/.DS_Store
  Kloudy/Kloudy/Network/CityWeatherNetwork.swift
  Server/apis/views.py
  Server/kloudy/networkAPI.py
  Server/kloudy/views.py
  Server/kloudy/weathers/CarWashIndex.py
  Server/kloudy/weathers/CompareIndex.py
  Server/kloudy/weathers/HourlyWeather.py
  Server/kloudy/weathers/LaundryIndex.py
  Server/kloudy/weathers/MainWeather.py
  Server/kloudy/weathers/OuterIndex.py
  Server/kloudy/weathers/UmbrellaIndex.py
  Server/kloudy/weathers/WeeklyWeather.py
Labels: Refactoring

#385 Feat[#367] : 토스트 메세지의 우선순위 변경
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement

#389 Bug[#386] WeatherKit 버그 수정
  Server/apis/views.py
  Server/kloudy/settings.py
  Server/kloudy/views.py
  Server/kloudy/weathers/HourlyWeather.py
  Server/kloudy/weathers/MainWeather.py
  Server/kloudy/weathers/UmbrellaIndex.py
Labels: bug

#391 Fix[#390] 일교차지수를 클릭할경우 꺼지는 문제
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: bug

#402 Fix: 스크롤뷰에서 Location Name에 localization을 더했습니다.
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
Labels: enhancement

#407 Feat[#393, #394, #395] : 데이터 추가
  Server/apis/migrations/0001_initial.py
  Server/apis/models.py
  Server/apis/serializers.py
  Server/apis/views.py
  Server/kloudy/csv/Locations.csv
  Server/kloudy/views.py
  Server/kloudy/weathers/CarWashIndex.py
  Server/kloudy/weathers/CompareIndex.py
  Server/kloudy/weathers/LaundryIndex.py
  Server/kloudy/weathers/MaskIndex.py
  Server/kloudy/weathers/UmbrellaIndex.py
Labels: enhancement

#406 Feat[#403] 제스쳐로 이전 페이지로 가는 기능 구현
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/Extension/UINavigationController+.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherViewModel.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: bug, enhancement

#405 Feat[#404] : 오픈소스라이센스 및 사용데이터 출처 웹 연결
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: enhancement

#409 Feat[#408] 겉옷지수 왼쪽하단 텍스트 추가
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/WeatherIndexView.swift
Labels: enhancement

#410 Feat[#397] : Weather Codable 구조체를 변경하고 빨래, 겉옷 지수 차트를 구현하였습니다.
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Model/Weather.swift
  Kloudy/Kloudy/Network/CityWeatherAPI.swift
  Kloudy/Kloudy/Network/FetchWeatherInformation.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorAssets/Orange02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexButtonView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexChartView/IndexChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: bug, enhancement

#413 Fix: LocationView의 셀 크기를 변경하였습니다.
  Kloudy/Kloudy/Resource/Assets.xcassets/deleteButton.imageset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/deleteButton.imageset/Frame 640.svg
  Kloudy/Kloudy/Resource/Assets.xcassets/deleteButton.imageset/deleteButton.svg
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
Labels: enhancement

#412 Feat[#411] 마스크차트뷰 추가
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexChartView/MaskChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: enhancement

#416 Feat[#415] : 세차 지수 차트를 구현하였습니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckLocation/LocationSelectionView/LocationSelectionView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/CarIndexChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: enhancement

#417 Style[#379] : 주간 날씨 오토레이아웃 수정
  Kloudy/Kloudy/View/CheckWeather/DetailWeatherView/DetailWeatherViewCollectionViewCells/WeekWeatherDataCell.swift.swift
Labels: enhancement

#419 Fix[#376, 418] MaskChartView Color, Font 변경, temperatureGapView 오토레이아웃 적용
  Kloudy/Kloudy/Extension/Color+.swift
  Kloudy/Kloudy/Extension/Font+.swift
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorAssets/ChartGreen01.colorset/Contents.json
  Kloudy/Kloudy/Resource/Assets.xcassets/ColorAssets/ChartGreen02.colorset/Contents.json
  Kloudy/Kloudy/Resource/Localization/en.lproj/Localizable.strings
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/InternalCheckWeatherPageView/InternalCheckWeatherPageView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/CarIndexChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexChartView/MaskChartView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/IndexIconView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexDetailView/WeatherIndexDetailView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/TemperatureGapView.swift
Labels: bug, enhancement, Refactoring

#421 Bug : Sprint3를 진행하면서 생긴 버그 수정
  Server/kloudy/scheduler/scheduler.py
  Server/kloudy/weathers/CarWashIndex.py
  Server/kloudy/weathers/LaundryIndex.py
  Server/kloudy/weathers/WeeklyWeather.py
Labels: bug

#424 Bug[#423] 겉옷지수를 누르면 앱이 꺼지는 버그 수정
  Kloudy/Kloudy/View/CheckWeather/WeatherIndexView/LocationWeatherIndexView/LocationWeatherIndexView.swift
Labels: bug

#429 Feat[#425] : 현재 위치 날씨 정보를 받아오지 않을 때에도 앱이 메인 화면으로 넘어가도록 합니다.
  Kloudy/Kloudy.xcodeproj/project.pbxproj
  Kloudy/Kloudy/Application/ViewController.swift
  Kloudy/Kloudy/UserDefaults/Storage.swift
  Kloudy/Kloudy/View/CheckWeather/CheckWeatherView/CheckWeatherView.swift
  Kloudy/Kloudy/View/Setting/SettingView.swift
Labels: enhancement
